### ISSUE TITLE
split into separate files

### ISSUE THREAD

**Issue by mayank99** [mayank99/open-props-scss#3]
having one giant `index.scss` is bad performance-wise so it might be useful to offer multiple entry points (one per category of props?) and forward them all in index

**Comment by WebMechanic** [comment]
the original open props are already split into distinct files, so: yes!
that's how we actually use them: pick and choose. PostCSS JIT doesn't work for us, 'cos we want to stick to multiple .css files per site sections and alsofor theming. 

I'm looking for some tool to filter the one we actually use _prior_ bundling, not after the fact, which doesn't work for us. 
Maybe this is it?

**Comment by mayank99** [comment]
@WebMechanic i do not think this issue will actually matter for your purpose (multiple .css files etc), because by default, even with this giant `index.scss`, your compiled css would only contain the values that you actually use.

but yes, this feature would be nice to have in general.

**Comment by woodcox** [comment]
Hi, i've sent a pull request that splits the scss into separate modules and also an `index.scss` that `@forward` the scss modules to the `index.scss`.

I hope this is helpful :). I wasn't sure where you wanted to put the scss modules within the file structure and whether you want to change the `custommedia.scss` to `media.scss` so that the naming is consistent with open-props.

**Comment by mayank99** [comment]
Thanks @woodcox, left a comment on the PR
